import Head from 'next/head'
import React from 'react'
import Country from '../components/Country'


export default function Home(props) {

  const countries = props.data

  const getData = (countryName) => {
    setCountry(countryName)
  }


  return (
    <div className="max-w-screen-xl mx-auto">
      <Head>
        <title>Dynamic and Protected Route</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-3">
        {
          countries.map(country => <Country key={country.alpha2Code} country={country} />)
        }
      </div>
    </div>
  )
}

export async function getStaticProps(context) {

  const res = await fetch('https://restcountries.eu/rest/v2/all')
  const data = await res.json()

  if (!data) {
    return {
      notFound: true
    }
  }

  return {
    props: {
      data
    }
  }


}
